import os
import re
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.responses import HTMLResponse
from groq import Groq

from intelligence_engine import (
    parse_whatsapp_transcript, 
    compute_transcript_stats, 
    analyze_relationship,
    get_valid_text_models
)

def _load_env():
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    if os.path.exists(env_path):
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, v = line.split('=', 1)
                    os.environ.setdefault(k.strip(), v.strip())

_load_env()

app = FastAPI(title="LifeBook - Evidence-Based Memoir Generator")

groq_key = os.environ.get("GROQ_API_KEY")
client = Groq(api_key=groq_key)


def get_max_allowed_transcript(chat_transcript: str, fraction: float) -> str:
    """
    Dynamically sizes the transcript. If fraction is 1.0, it returns 100% of the chat.
    If less than 1.0, it perfectly balances the start, middle, and end to fit the API limit.
    """
    if fraction >= 1.0:
        return chat_transcript

    target_length = int(len(chat_transcript) * fraction)
    segment_size = target_length // 3
    
    beginning = chat_transcript[:segment_size]
    mid_start = (len(chat_transcript) // 2) - (segment_size // 2)
    middle = chat_transcript[mid_start : mid_start + segment_size]
    end = chat_transcript[-segment_size:]

    return (
        f"--- EARLY CHAT PERIOD ---\n{beginning}\n\n"
        f"--- MIDDLE CHAT PERIOD ---\n{middle}\n\n"
        f"--- RECENT CHAT PERIOD ---\n{end}"
    )


def markdown_to_html(md_text: str) -> str:
    """Converts markdown generated by LLM into clean HTML."""
    html_lines = []
    in_paragraph = False

    for line in md_text.splitlines():
        line_str = line.strip()

        if not line_str:
            if in_paragraph:
                html_lines.append("</p>")
                in_paragraph = False
            continue

        if line_str.startswith("# "):
            if in_paragraph: html_lines.append("</p>"); in_paragraph = False
            html_lines.append(f"<h1>{line_str[2:]}</h1>")
            continue
        elif line_str.startswith("## "):
            if in_paragraph: html_lines.append("</p>"); in_paragraph = False
            html_lines.append(f"<h2>{line_str[3:]}</h2>")
            continue
        elif line_str.startswith("### "):
            if in_paragraph: html_lines.append("</p>"); in_paragraph = False
            html_lines.append(f"<h3>{line_str[4:]}</h3>")
            continue

        line_str = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', line_str)
        line_str = re.sub(r'\*(.*?)\*', r'<em>\1</em>', line_str)

        if not in_paragraph:
            html_lines.append("<p>")
            in_paragraph = True
            html_lines.append(line_str)
        else:
            html_lines.append(f" {line_str}")

    if in_paragraph:
        html_lines.append("</p>")

    return "\n".join(html_lines)


@app.get("/", response_class=HTMLResponse)
async def main_page():
    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LifeBook — Memoir Generator</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
        <style>
            * { box-sizing: border-box; }
            body { 
                font-family: 'Inter', system-ui, -apple-system, sans-serif; 
                background: #0f172a; 
                color: #f8fafc; 
                min-height: 100vh; 
                margin: 0; 
                display: flex; 
                justify-content: center; 
                align-items: center; 
                padding: 24px; 
            }
            .card { 
                background: #1e293b; 
                border: 1px solid #334155; 
                padding: 48px 40px; 
                border-radius: 20px; 
                box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5); 
                width: 100%; 
                max-width: 520px; 
            }
            .badge {
                display: inline-block;
                background: #38bdf81a;
                color: #38bdf8;
                font-weight: 600;
                font-size: 12px;
                padding: 4px 12px;
                border-radius: 9999px;
                text-transform: uppercase;
                letter-spacing: 0.05em;
                margin-bottom: 12px;
            }
            h1 { margin: 0 0 8px 0; font-size: 32px; font-weight: 700; color: #ffffff; letter-spacing: -0.02em; }
            p.subtitle { color: #94a3b8; font-size: 15px; margin-top: 0; margin-bottom: 32px; line-height: 1.5; }
            .form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
            input[type="text"] { 
                width: 100%; 
                padding: 12px 16px; 
                border: 1px solid #334155; 
                border-radius: 10px; 
                font-size: 14px; 
                background: #0f172a; 
                color: #ffffff; 
                outline: none;
                transition: border-color 0.2s;
            }
            input[type="text"]:focus { border-color: #38bdf8; }
            .file-box { 
                margin: 16px 0 24px 0; 
                padding: 28px 16px; 
                border: 2px dashed #475569; 
                border-radius: 12px; 
                cursor: pointer; 
                background: #0f172a50; 
                text-align: center; 
                color: #94a3b8; 
                font-size: 14px; 
                transition: all 0.2s;
            }
            .file-box:hover { border-color: #38bdf8; color: #e2e8f0; }
            button { 
                background: #38bdf8; 
                color: #0f172a; 
                border: none; 
                padding: 16px; 
                font-size: 16px; 
                border-radius: 10px; 
                cursor: pointer; 
                width: 100%; 
                font-weight: 700; 
                transition: background 0.2s; 
            }
            button:hover { background: #7dd3fc; }
            .loading-container { display: none; text-align: center; margin-top: 24px; }
            .spinner { 
                border: 3px solid #334155; 
                border-top: 3px solid #38bdf8; 
                border-radius: 50%; 
                width: 28px; 
                height: 28px; 
                animation: spin 0.8s linear infinite; 
                margin: 0 auto 12px auto; 
            }
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
            #loading-text { font-size: 14px; color: #94a3b8; font-weight: 500; }
        </style>
    </head>
    <body>
        <div class="card">
            <span class="badge">LifeBook MVP</span>
            <h1>Memoir Generator</h1>
            <p class="subtitle">Transform WhatsApp export logs into an evidence-bound narrative chapter.</p>
            
            <form action="/generate" enctype="multipart/form-data" method="post" onsubmit="showLoading()">
                <div class="form-grid">
                    <input type="text" name="user_name" placeholder="Your Name" required>
                    <input type="text" name="user_pronouns" placeholder="Pronouns (she/her)" required>
                </div>
                <div class="form-grid">
                    <input type="text" name="other_name" placeholder="Their Name" required>
                    <input type="text" name="other_pronouns" placeholder="Pronouns (he/him)" required>
                </div>
                
                <input class="file-box" name="file" type="file" accept=".txt" required>
                
                <button type="submit" id="submit-btn">Generate Chapter</button>
            </form>
            
            <div id="loading" class="loading-container">
                <div class="spinner"></div>
                <div id="loading-text">Parsing WhatsApp structure...</div>
            </div>
        </div>
        
        <script>
            function showLoading() {
                document.getElementById('submit-btn').style.display = 'none';
                document.getElementById('loading').style.display = 'block';
                const steps = [
                    "Parsing chat timestamps...",
                    "Filtering system notifications...",
                    "Analyzing 100% of conversation timeline...",
                    "Maximizing API Context Window...",
                    "Composing long-form narrative..."
                ];
                let idx = 0;
                setInterval(() => {
                    idx = (idx + 1) % steps.length;
                    document.getElementById('loading-text').innerText = steps[idx];
                }, 2200);
            }
        </script>
    </body>
    </html>
    """


@app.post("/generate", response_class=HTMLResponse)
async def generate_story_endpoint(
    file: UploadFile = File(...),
    user_name: str = Form(...),
    user_pronouns: str = Form(...),
    other_name: str = Form(...),
    other_pronouns: str = Form(...)
):
    if not file.filename.endswith('.txt'):
        raise HTTPException(status_code=400, detail="Only exported .txt chat files are accepted.")

    raw_bytes = await file.read()
    decoded_text = raw_bytes.decode('utf-8', errors='ignore')

    structured_data = parse_whatsapp_transcript(decoded_text)
    if not structured_data:
        return """
        <div style="font-family:sans-serif; text-align:center; padding:50px;">
            <h2>Could not parse any messages from this file.</h2>
            <p>Ensure you are uploading an unedited exported WhatsApp .txt file.</p>
            <a href="/">← Try Again</a>
        </div>
        """

    chat_transcript = "\n".join(
        f"[{m['date']}] {m['sender']}: {m['message']}" for m in structured_data
    )

    stats = compute_transcript_stats(structured_data)

    try:
        profile = analyze_relationship(client, chat_transcript, stats)
    except Exception as e:
        return f"<div style='padding:40px; font-family:sans-serif;'><h3>Intelligence Analysis Error:</h3><p>{str(e)}</p><a href='/'>Go back</a></div>"

    conn_description = profile.get('connection_description', 'A digital correspondence.')
    observed_activity = profile.get('observed_activity', 'Activity documented across transcript span.')
    verbatim_quotes = ", ".join(f'"{q}"' for q in profile.get('key_verbatim_quotes', []))
    specific_topics = ", ".join(profile.get('specific_topics_and_events', ['General exchanges']))
    turning_points = ", ".join(profile.get('turning_points', ['None noted']))
    communication_changes = ", ".join(profile.get('communication_changes', ['None noted']))

    system_prompt = f"""
    You are an expert biographer writing a detailed, chronological memoir chapter based strictly on a WhatsApp chat transcript.

    PARTICIPANTS:
    - Participant 1: {user_name} (Pronouns: {user_pronouns})
    - Participant 2: {other_name} (Pronouns: {other_pronouns})

    STATISTICS:
    - Total Messages: {stats['total_messages']}
    - Date Range: {stats['first_message_date']} to {stats['last_message_date']} ({stats['span_days']} days total)
    - Longest Gap: {stats['longest_communication_gap_days']} days

    METADATA ANALYSIS:
    - Connection Style: {conn_description}
    - Observed Timeline: {observed_activity}
    - Key Verbatim Quotes: {verbatim_quotes}
    - Major Topics Discussed: {specific_topics}
    - Key Moments & Shifts: {turning_points}
    - Response Pacing: {communication_changes}

    WRITING RULES:
    1. SIMPLE TITLE: Start with a simple, concise Markdown header `# Title` based directly on the main theme or overall subject of the chat.
    2. SUBSTANTIAL & DETAILED STORY: Write a full, long-form narrative consisting of 4 to 6 substantial paragraphs. Thoroughly detail what occurred, what was discussed, decisions made, and how events unfolded over time.
    3. STRICT CHRONOLOGICAL FLOW: Follow the story step-by-step in the order events happened, moving sequentially from the earliest messages in the transcript, through the middle discussions, to the final exchanges.
    4. NO EMOJIS: Do NOT include any emojis anywhere in the title or narrative text. Zero emojis.
    5. COMPLETE COVERAGE: Read through ALL sections of the transcript provided so no major part of the timeline is omitted.
    6. VERBATIM QUOTES: Integrate real verbatim quotes seamlessly into paragraphs with quotation marks to ground the story in factual evidence.
    7. ZERO FABRICATION & NO AI CLICHÉS: Only recount facts present in the text. Avoid generic AI cliché words.
    """

    models = get_valid_text_models(client)
    story_md = None

    for model in models:
        fraction = 1.0  # Start by trying 100% of the entire chat
        
        while fraction > 0.1:
            transcript_sample = get_max_allowed_transcript(chat_transcript, fraction)
            print(f"[Narrative Engine] Attempting to process {(fraction*100):.0f}% of chat with {model}...")
            
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": f"Full Timeline Transcript:\n\n{transcript_sample}"}
                    ],
                    temperature=0.35,
                    max_tokens=2500
                )
                story_md = response.choices[0].message.content
                print(f"[Success] Generated narrative using {(fraction*100):.0f}% of the chat log!")
                break # Success! Break out of the while loop
                
            except Exception as e:
                error_msg = str(e).lower()
                # If the API says the file is too big, shrink it by 20% and try again immediately
                if "too large" in error_msg or "rate limit" in error_msg or "tokens" in error_msg or "rate_limit_exceeded" in error_msg:
                    print(f"[-] Groq rejected file size. Scaling down...")
                    fraction -= 0.20
                else:
                    print(f"[-] Model {model} failed for another reason: {e}")
                    break # Break while loop, try the next model in the list
                    
        if story_md:
            break # Success! Break out of the model loop

    if not story_md:
        return "<div style='padding:40px; font-family:sans-serif;'><h3>Narrative Generation Error:</h3><p>All accessible models failed to generate narrative, or the file size could not be scaled down enough to fit the API limits.</p><a href='/'>Go back</a></div>"

    rendered_html = markdown_to_html(story_md)

    return f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LifeBook — {user_name} & {other_name}</title>
        <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,700;1,6..72,400&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
        <style>
            body {{
                font-family: 'Newsreader', Georgia, serif;
                background-color: #f8fafc;
                color: #0f172a;
                margin: 0;
                padding: 60px 20px;
                display: flex;
                justify-content: center;
                line-height: 1.8;
            }}
            .book-container {{
                background: #ffffff;
                padding: 80px 100px;
                max-width: 760px;
                width: 100%;
                box-shadow: 0 10px 40px rgba(0,0,0,0.04);
                border: 1px solid #e2e8f0;
                border-radius: 4px;
            }}
            h1 {{
                font-size: 38px;
                font-weight: 700;
                color: #0f172a;
                margin-top: 0;
                margin-bottom: 32px;
                line-height: 1.25;
                border-bottom: 2px solid #0f172a;
                padding-bottom: 24px;
                letter-spacing: -0.02em;
            }}
            h2 {{ font-size: 24px; margin-top: 40px; color: #1e293b; font-weight: 600; }}
            p {{ font-size: 19px; margin-bottom: 28px; color: #334155; text-align: justify; }}
            strong {{ color: #0f172a; }}
            .actions {{
                margin-top: 60px;
                padding-top: 30px;
                border-top: 1px solid #e2e8f0;
                display: flex;
                gap: 16px;
                font-family: 'Inter', sans-serif;
            }}
            .btn {{
                padding: 12px 20px;
                border-radius: 8px;
                font-weight: 600;
                font-size: 14px;
                text-decoration: none;
                cursor: pointer;
                border: none;
                transition: all 0.2s;
            }}
            .btn-primary {{ background: #0f172a; color: #ffffff; }}
            .btn-primary:hover {{ background: #1e293b; }}
            .btn-secondary {{ background: #f1f5f9; color: #475569; }}
            .btn-secondary:hover {{ background: #e2e8f0; }}

            @media print {{
                body {{ background: white; padding: 0; }}
                .book-container {{ box-shadow: none; border: none; padding: 0; max-width: 100%; }}
                .actions {{ display: none; }}
            }}
            @media (max-width: 640px) {{
                .book-container {{ padding: 40px 24px; }}
                h1 {{ font-size: 28px; }}
                p {{ font-size: 17px; }}
            }}
        </style>
    </head>
    <body>
        <div class="book-container">
            {rendered_html}
            
            <div class="actions">
                <button class="btn btn-primary" onclick="window.print()">Print / Save PDF</button>
                <a href="/" class="btn btn-secondary">← Upload Another Chat</a>
            </div>
        </div>
    </body>
    </html>
    """